development:
  adapter: mysql2
  database: cloudserver_development
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: cloudserver
  username: admin
  host: cloudserver.csmtof4sowot.ap-southeast-1.rds.amazonaws.com
  password: mypassword
  port: 3306
  pool: 5
  timeout: 5000
