development:
  adapter: mysql2
  database: cloudserver_development
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: <database-name>
  username: <username>
  host: <rds url>
  password: <password>
  port: 3306
  pool: 5
  timeout: 5000
